const {Client,GatewayIntentBits,PermissionsBitField,AuditLogEvent,EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,StringSelectMenuBuilder,ChannelSelectMenuBuilder,ChannelType,RoleSelectMenuBuilder,ModalBuilder,TextInputBuilder,TextInputStyle,AttachmentBuilder}=require("discord.js");
const fs=require("fs"), TOKEN=process.env.DISCORD_TOKEN||"COLE_SEU_NOVO_TOKEN_AQUI", PREFIX=".", DB="./database.json";
let db={};try{if(fs.existsSync(DB))db=JSON.parse(fs.readFileSync(DB,"utf8"))}catch(e){console.log(e)}
const save=()=>fs.writeFileSync(DB,JSON.stringify(db,null,2));
function D(id){if(!db[id])db[id]={anti:{on:false,perms:false,roles:false,log:null,white:[]},auto:{on:false,ch:null,msg:"",min:10,n:1,last:[]},tickets:{staff:[],open:null,close:null,cats:{},owners:{},stats:{}},analyst:{roles:[],request:[],ch:null,log:null,stats:{},active:{}},lock:{roles:[]}};save();return db[id]}
const bot=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildMessages,GatewayIntentBits.MessageContent,GatewayIntentBits.GuildMembers]});
const admin=m=>m.id===m.guild.ownerId||m.permissions.has(PermissionsBitField.Flags.Administrator);
const staff=(m,d)=>admin(m)||d.tickets.staff.some(x=>m.roles.cache.has(x));
const analyst=(m,d)=>admin(m)||d.analyst.roles.some(x=>m.roles.cache.has(x));
const requester=(m,d)=>admin(m)||d.analyst.request.some(x=>m.roles.cache.has(x));
const clean=x=>String(x).toLowerCase().replace(/[^a-z0-9-_]/g,"-").replace(/-+/g,"-").slice(0,90)||"ticket";
const danger=[PermissionsBitField.Flags.Administrator,PermissionsBitField.Flags.ManageGuild,PermissionsBitField.Flags.ManageRoles,PermissionsBitField.Flags.ManageChannels,PermissionsBitField.Flags.ManageWebhooks,PermissionsBitField.Flags.BanMembers,PermissionsBitField.Flags.KickMembers];
async function anti(g,text){let c=g.channels.cache.get(D(g.id).anti.log);if(c?.isTextBased())await c.send({embeds:[new EmbedBuilder().setTitle("🛡️ Anti-Nuke").setDescription(text).setTimestamp()]}).catch(()=>{})}
async function punish(g,id,why){let d=D(g.id);if(!d.anti.on||id===g.ownerId||id===bot.user.id||d.anti.white.includes(id))return;let m=await g.members.fetch(id).catch(()=>null);if(m?.kickable){await m.kick(why).catch(()=>{});await anti(g,`**Infrator:** <@${id}>\n**Penalidade:** Kick\n**Motivo:** ${why}`)}else await anti(g,`**Infrator:** <@${id}>\n**Motivo:** ${why}\nNão foi possível kickar.`)}
async function executor(g,type,target){let x=await g.fetchAuditLogs({type,limit:5}).catch(()=>null);let e=x?.entries.find(z=>z.target?.id===target&&Date.now()-z.createdTimestamp<15000);return e?.executor}
bot.on("roleUpdate",async(a,b)=>{let d=D(b.guild.id);if(!d.anti.on||!d.anti.perms||!danger.some(p=>!a.permissions.has(p)&&b.permissions.has(p)))return;let u=await executor(b.guild,AuditLogEvent.RoleUpdate,b.id);if(u)punish(b.guild,u.id,`Permissão perigosa em ${b.name}`)});
bot.on("roleCreate",async r=>{let d=D(r.guild.id);if(!d.anti.on||!d.anti.roles||!danger.some(p=>r.permissions.has(p)))return;let u=await executor(r.guild,AuditLogEvent.RoleCreate,r.id);if(u)punish(r.guild,u.id,`Cargo perigoso criado: ${r.name}`)});
function row(...x){return new ActionRowBuilder().addComponents(...x)}
function btn(id,label,style){return new ButtonBuilder().setCustomId(id).setLabel(label).setStyle(style)}
function modal(id,title,fields){let m=new ModalBuilder().setCustomId(id).setTitle(title);m.addComponents(...fields.map(f=>row(new TextInputBuilder().setCustomId(f[0]).setLabel(f[1]).setStyle(f[2]||TextInputStyle.Short).setRequired(f[3]??true).setValue(f[4]||""))));return m}
function main(){return row(new StringSelectMenuBuilder().setCustomId("main").setPlaceholder("Configurar").addOptions({label:"Tickets",value:"t"},{label:"Mensagem automática",value:"a"},{label:"Anti-Nuke",value:"n"},{label:"Analistas",value:"s"},{label:"Lock",value:"l"}))}
function tpanel(){return row(btn("take","Assumir",ButtonStyle.Primary),btn("add","Adicionar",ButtonStyle.Secondary),btn("rem","Remover",ButtonStyle.Secondary),btn("rename","Renomear",ButtonStyle.Secondary),btn("close","Fechar",ButtonStyle.Danger))}
async function openTicket(i,id){let d=D(i.guild.id),c=d.tickets.cats[id];if(!c)return i.reply({content:"❌ Catálogo inválido.",ephemeral:true});let ex=Object.entries(d.tickets.owners).find(([,v])=>v.user===i.user.id&&v.cat===id);if(ex&&i.guild.channels.cache.has(ex[0]))return i.reply({content:`❌ Você já possui: <#${ex[0]}>`,ephemeral:true});let ch;
if(c.mode==="forum"){let f=i.guild.channels.cache.get(c.target);if(!f||f.type!==ChannelType.GuildForum)return i.reply({content:"❌ Fórum inválido.",ephemeral:true});ch=await f.threads.create({name:clean(`${c.name}-${i.user.username}`),message:{content:`${i.user}`,embeds:[new EmbedBuilder().setTitle(c.name).setDescription(c.desc||"Ticket aberto")]}})}
else{let cat=i.guild.channels.cache.get(c.target);if(!cat||cat.type!==ChannelType.GuildCategory)return i.reply({content:"❌ Categoria inválida.",ephemeral:true});ch=await i.guild.channels.create({name:clean(`${c.name}-${i.user.username}`),type:ChannelType.GuildText,parent:cat.id,permissionOverwrites:[{id:i.guild.roles.everyone.id,deny:[PermissionsBitField.Flags.ViewChannel]},{id:i.user.id,allow:[PermissionsBitField.Flags.ViewChannel,PermissionsBitField.Flags.SendMessages,PermissionsBitField.Flags.ReadMessageHistory]},...d.tickets.staff.map(r=>({id:r,allow:[PermissionsBitField.Flags.ViewChannel,PermissionsBitField.Flags.SendMessages,PermissionsBitField.Flags.ReadMessageHistory]}))]})}
d.tickets.owners[ch.id]={user:i.user.id,cat:id,by:null};save();let e=new EmbedBuilder().setTitle(`🎫 ${c.name}`).setDescription(`${c.desc||""}\n\nUsuário: ${i.user}`).setTimestamp();if(/^https?:\/\//i.test(c.image||""))e.setImage(c.image);await ch.send({content:`${i.user} ${d.tickets.staff.map(x=>`<@&${x}>`).join(" ")}`,embeds:[e],components:[tpanel()]});let l=i.guild.channels.cache.get(d.tickets.open);if(l?.isTextBased())l.send(`🎫 Ticket aberto: ${ch} | ${i.user}`).catch(()=>{});return i.reply({content:`✅ Aberto: ${ch}`,ephemeral:true})}
const timers=new Map();function auto(gid){if(timers.has(gid))clearInterval(timers.get(gid));let f=async()=>{let a=D(gid).auto;if(!a.on||!a.ch||!a.msg)return;let c=bot.channels.cache.get(a.ch);if(!c?.isTextBased())return;for(let id of a.last)await c.messages.delete(id).catch(()=>{});a.last=[];for(let z=0;z<Math.min(20,Math.max(1,a.n));z++){let m=await c.send({content:a.msg,allowedMentions:{parse:["users","roles","everyone"]}}).catch(()=>null);if(m)a.last.push(m.id)}save()};timers.set(gid,setInterval(f,Math.max(1,D(gid).auto.min)*60000))}
bot.once("ready",()=>{console.log(`Online: ${bot.user.tag}`);Object.keys(db).forEach(auto)});
bot.on("messageCreate",async m=>{if(!m.guild||m.author.bot)return;let d=D(m.guild.id),x=m.content.trim();
if(x===PREFIX+"config"){if(!admin(m.member))return m.reply("❌ Apenas administrador.");return m.channel.send({content:"⚙️ Painel",components:[main()]})}
if(x===PREFIX+"ping")return m.reply(`🏓 ${bot.ws.ping}ms`);
if(x===PREFIX+"painelticket"){if(!admin(m.member))return;let a=Object.entries(d.tickets.cats).filter(([,c])=>c.target).slice(0,25);if(!a.length)return m.reply("Crie um catálogo em `.config`.");return m.channel.send({embeds:[new EmbedBuilder().setTitle("🎫 Central de Atendimento")],components:[row(new StringSelectMenuBuilder().setCustomId("open").setPlaceholder("Escolha").addOptions(a.map(([id,c])=>({label:c.name,value:id,description:(c.desc||"Abrir").slice(0,100),emoji:c.emoji||"🎫"}))))]})}
if(x===PREFIX+"rankingtickets"){let r=Object.entries(d.tickets.stats).sort((a,b)=>b[1]-a[1]);return m.channel.send(r.length?r.map(([id,n],i)=>`${i+1}. <@${id}> — ${n}`).join("\n"):"Sem dados.")}
if(x===PREFIX+"rankinganalista"){let r=Object.entries(d.analyst.stats).sort((a,b)=>b[1]-a[1]);return m.channel.send(r.length?r.map(([id,n],i)=>`${i+1}. <@${id}> — ${n}`).join("\n"):"Sem dados.")}
if(x===PREFIX+"lock"){if(!m.member.permissions.has(PermissionsBitField.Flags.ManageMessages))return;m.channel.permissionOverwrites.edit(m.guild.roles.everyone.id,{SendMessages:false});for(let r of d.lock.roles)m.channel.permissionOverwrites.edit(r,{SendMessages:true}).catch(()=>{});return m.reply("🔒 Trancado.")}
if(x===PREFIX+"unlock"){if(!m.member.permissions.has(PermissionsBitField.Flags.ManageMessages))return;await m.channel.permissionOverwrites.edit(m.guild.roles.everyone.id,{SendMessages:null});return m.reply("🔓 Destrancado.")}
if(x===PREFIX+"ssmob"||x===PREFIX+"ssemu"){if(!requester(m.member,d)||!d.analyst.ch)return m.reply("❌ Solicitação não permitida/configurada.");let id=`a${Date.now()}`,type=x.slice(1),c=m.guild.channels.cache.get(d.analyst.ch);d.analyst.active[id]={user:m.author.id,ch:m.channel.id,type,by:null,done:false};save();return c.send({content:`🔎 **${type.toUpperCase()}** solicitado por ${m.author}\nCanal: ${m.channel}`,components:[row(btn(`accept:${id}`,"Aceitar análise",ButtonStyle.Success))]})}
let [cmd]=x.split(/\s+/),u=m.mentions.members.first();if([".ban",".kick",".mute"].includes(cmd)&&u&&m.member.permissions.has(PermissionsBitField.Flags.ManageMessages)){if(cmd===".ban"&&u.bannable){await u.ban();return m.reply("🔨 Banido.")}if(cmd===".kick"&&u.kickable){await u.kick();return m.reply("👢 Expulso.")}if(cmd===".mute"){let r=m.guild.roles.cache.find(r=>["mute","muted"].includes(r.name.toLowerCase()));if(!r)return m.reply("Crie o cargo `Muted`.");await u.roles.add(r);return m.reply("🔇 Silenciado.")}}});
bot.on("interactionCreate",async i=>{try{if(!i.guild)return;let d=D(i.guild.id);
if(i.isStringSelectMenu()&&i.customId==="main"){if(!admin(i.member))return i.reply({content:"❌ Sem permissão.",ephemeral:true});let v=i.values[0];
if(v==="t")return i.update({content:"🎫 Tickets",components:[row(btn("cat","Criar catálogo",ButtonStyle.Success),btn("staff","Cargos staff",ButtonStyle.Primary),btn("tlogs","Logs",ButtonStyle.Secondary))]});
if(v==="a")return i.update({content:`📢 ${d.auto.on?"ATIVADO":"DESATIVADO"}`,components:[row(btn("autocfg","Configurar",ButtonStyle.Primary),btn("autoon","Ativar/Desativar",ButtonStyle.Success))]});
if(v==="n")return i.update({content:`🛡️ ${d.anti.on?"ATIVADO":"DESATIVADO"}`,components:[row(btn("non","Ativar/Desativar",ButtonStyle.Success),btn("nperm","Permissões",ButtonStyle.Secondary),btn("nrole","Cargos perigosos",ButtonStyle.Secondary))]});
if(v==="s")return i.update({content:"🔎 Analistas",components:[row(btn("arole","Cargo analista",ButtonStyle.Primary),btn("reqrole","Quem solicita",ButtonStyle.Primary),btn("achan","Canais",ButtonStyle.Secondary))]});
if(v==="l")return i.update({content:"🔒 Cargos do lock",components:[row(new RoleSelectMenuBuilder().setCustomId("lockroles").setMinValues(0).setMaxValues(25))]})}
if(i.isStringSelectMenu()&&i.customId==="open")return openTicket(i,i.values[0]);
if(i.isStringSelectMenu()&&i.customId.startsWith("mode:")){let id=i.customId.slice(5);d.tickets.cats[id].mode=i.values[0];save();return i.update({content:"Selecione o destino.",components:[row(new ChannelSelectMenuBuilder().setCustomId(`target:${id}`).addChannelTypes(i.values[0]==="forum"?ChannelType.GuildForum:ChannelType.GuildCategory))]})}
if(i.isRoleSelectMenu()){if(!admin(i.member))return i.reply({content:"❌ Sem permissão.",ephemeral:true});if(i.customId==="staff")d.tickets.staff=i.values;if(i.customId==="arole")d.analyst.roles=i.values;if(i.customId==="reqrole")d.analyst.request=i.values;if(i.customId==="lockroles")d.lock.roles=i.values;save();return i.update({content:"✅ Salvo.",components:[]})}
if(i.isChannelSelectMenu()){if(!admin(i.member))return i.reply({content:"❌ Sem permissão.",ephemeral:true});let id=i.values[0];if(i.customId.startsWith("target:"))d.tickets.cats[i.customId.slice(7)].target=id;else if(i.customId==="topen")d.tickets.open=id;else if(i.customId==="tclose")d.tickets.close=id;else if(i.customId==="areq")d.analyst.ch=id;else if(i.customId==="alog")d.analyst.log=id;save();return i.update({content:"✅ Salvo.",components:[]})}
if(i.isButton()){let inf=d.tickets.owners[i.channel.id];
if(i.customId==="cat")return i.showModal(modal("catmodal","Criar catálogo",[["name","Nome"],["desc","Descrição",TextInputStyle.Paragraph],["emoji","Emoji",TextInputStyle.Short,false],["image","Link da imagem",TextInputStyle.Short,false]]));
if(i.customId==="staff")return i.reply({content:"Selecione.",components:[row(new RoleSelectMenuBuilder().setCustomId("staff").setMinValues(1).setMaxValues(25))],ephemeral:true});
if(i.customId==="tlogs")return i.reply({content:"Selecione os logs.",components:[row(new ChannelSelectMenuBuilder().setCustomId("topen").setPlaceholder("Abertura").addChannelTypes(ChannelType.GuildText)),row(new ChannelSelectMenuBuilder().setCustomId("tclose").setPlaceholder("Fechamento").addChannelTypes(ChannelType.GuildText))],ephemeral:true});
if(i.customId==="autocfg")return i.showModal(modal("automodal","Mensagem automática",[["msg","Mensagem",TextInputStyle.Paragraph],["min","Intervalo em minutos"],["qty","Quantidade 1-20"]]));
if(i.customId==="autoon"){d.auto.on=!d.auto.on;save();auto(i.guild.id);return i.reply({content:d.auto.on?"✅ Ativada":"❌ Desativada",ephemeral:true})}
if(i.customId==="non"){d.anti.on=!d.anti.on;save();return i.reply({content:`🛡️ ${d.anti.on?"Ativado":"Desativado"}`,ephemeral:true})}
if(i.customId==="nperm"){d.anti.perms=!d.anti.perms;save();return i.reply({content:`Permissões: ${d.anti.perms?"ON":"OFF"}`,ephemeral:true})}
if(i.customId==="nrole"){d.anti.roles=!d.anti.roles;save();return i.reply({content:`Cargos: ${d.anti.roles?"ON":"OFF"}`,ephemeral:true})}
if(i.customId==="arole")return i.reply({content:"Selecione.",components:[row(new RoleSelectMenuBuilder().setCustomId("arole").setMinValues(1).setMaxValues(25))],ephemeral:true});
if(i.customId==="reqrole")return i.reply({content:"Selecione.",components:[row(new RoleSelectMenuBuilder().setCustomId("reqrole").setMinValues(1).setMaxValues(25))],ephemeral:true});
if(i.customId==="achan")return i.reply({content:"Selecione canais.",components:[row(new ChannelSelectMenuBuilder().setCustomId("areq").setPlaceholder("Solicitações").addChannelTypes(ChannelType.GuildText)),row(new ChannelSelectMenuBuilder().setCustomId("alog").setPlaceholder("Logs").addChannelTypes(ChannelType.GuildText))],ephemeral:true});
if(i.customId==="take"){if(!inf||!staff(i.member,d))return i.reply({content:"❌ Sem permissão.",ephemeral:true});if(inf.by)return i.reply({content:"❌ Já assumido.",ephemeral:true});inf.by=i.user.id;d.tickets.stats[i.user.id]=(d.tickets.stats[i.user.id]||0)+1;save();return i.reply(`👤 Assumido por ${i.user}`)}
if(i.customId==="add"&&staff(i.member,d))return i.showModal(modal("addmodal","Adicionar usuário",[["user","ID do usuário"]]));
if(i.customId==="rem"&&staff(i.member,d))return i.showModal(modal("remmodal","Remover usuário",[["user","ID do usuário"]]));
if(i.customId==="rename"&&staff(i.member,d))return i.showModal(modal("renmodal","Renomear",[["name","Novo nome"]]));
if(i.customId==="close"){if(!inf||!staff(i.member,d))return i.reply({content:"❌ Sem permissão.",ephemeral:true});await i.reply("🔒 Fechando...");let msgs=await i.channel.messages.fetch({limit:100}),file=new AttachmentBuilder(Buffer.from([...msgs.values()].reverse().map(m=>`${m.author.tag}: ${m.content}`).join("\n")||"Sem mensagens."),{name:`transcript-${i.channel.id}.txt`}),l=i.guild.channels.cache.get(d.tickets.close);if(l?.isTextBased())await l.send({content:`Ticket de <@${inf.user}>`,files:[file]}).catch(()=>{});delete d.tickets.owners[i.channel.id];save();return setTimeout(()=>i.channel.delete().catch(()=>{}),1500)}
if(i.customId.startsWith("accept:")){let id=i.customId.slice(7),a=d.analyst.active[id];if(!a||!analyst(i.member,d))return i.reply({content:"❌ Sem permissão.",ephemeral:true});if(a.by)return i.reply({content:"❌ Já aceita.",ephemeral:true});a.by=i.user.id;d.analyst.stats[i.user.id]=(d.analyst.stats[i.user.id]||0)+1;save();let c=i.guild.channels.cache.get(a.ch);if(c)await c.permissionOverwrites.edit(i.user.id,{ViewChannel:true,SendMessages:true,ReadMessageHistory:true});await i.update({content:`🔎 Aceita por ${i.user}`,components:[]});return c?.send({content:`🔎 Análise aceita por ${i.user}`,components:[row(btn(`clean:${id}`,"Limpo",ButtonStyle.Success),btn(`wo:${id}`,"W.O",ButtonStyle.Danger))]})}
if(i.customId.startsWith("clean:")||i.customId.startsWith("wo:")){let [k,id]=i.customId.split(":"),a=d.analyst.active[id];if(!a||a.by!==i.user.id)return i.reply({content:"❌ Apenas quem aceitou.",ephemeral:true});a.done=true;a.result=k==="clean"?"LIMPO":"W.O";save();let l=i.guild.channels.cache.get(d.analyst.log);if(l?.isTextBased())l.send(`🔎 ${a.result} | <@${a.user}> | ${i.user}`).catch(()=>{});return i.update({content:`${a.result==="LIMPO"?"✅":"⚠️"} Analista ${i.user} definiu como **${a.result}**.`,components:[]})}}
if(i.isModalSubmit()){if(i.customId==="catmodal"){let id=`c${Date.now()}`;d.tickets.cats[id]={name:i.fields.getTextInputValue("name"),desc:i.fields.getTextInputValue("desc"),emoji:i.fields.getTextInputValue("emoji")||"🎫",image:i.fields.getTextInputValue("image")||"",mode:null,target:null};save();return i.reply({content:"Categoria ou Fórum?",components:[row(new StringSelectMenuBuilder().setCustomId(`mode:${id}`).addOptions({label:"Categoria",value:"category"},{label:"Fórum",value:"forum"}))],ephemeral:true})}
if(i.customId==="automodal"){d.auto.msg=i.fields.getTextInputValue("msg");d.auto.min=Math.max(1,Number(i.fields.getTextInputValue("min"))||10);d.auto.n=Math.min(20,Math.max(1,Number(i.fields.getTextInputValue("qty"))||1));d.auto.ch=i.channel.id;save();if(d.auto.on)auto(i.guild.id);return i.reply({content:"✅ Configurado neste canal.",ephemeral:true})}
if(i.customId==="addmodal"){let id=i.fields.getTextInputValue("user").trim();await i.channel.permissionOverwrites.edit(id,{ViewChannel:true,SendMessages:true,ReadMessageHistory:true});return i.reply({content:`✅ <@${id}> adicionado.`,ephemeral:true})}
if(i.customId==="remmodal"){let id=i.fields.getTextInputValue("user").trim();await i.channel.permissionOverwrites.delete(id).catch(()=>{});return i.reply({content:`✅ <@${id}> removido.`,ephemeral:true})}
if(i.customId==="renmodal"){let n=clean(i.fields.getTextInputValue("name"));await i.channel.setName(n);return i.reply({content:`✅ ${n}`,ephemeral:true})}}
}catch(e){console.error(e);if(i.isRepliable()&&!i.replied&&!i.deferred)i.reply({content:"❌ Erro. Veja o Termux.",ephemeral:true}).catch(()=>{})}});
if(!TOKEN||TOKEN==="COLE_SEU_NOVO_TOKEN_AQUI")console.log("Defina DISCORD_TOKEN ou coloque o token em TOKEN.");else bot.login(TOKEN).catch(e=>console.error("Erro no login:",e.message));
